// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"test/pkg/models/shared"
)

type ExecuteTaskQueryParams struct {
	// Environment to execute the task in.
	EnvSlug *string `queryParam:"style=form,explode=true,name=envSlug"`
}

type ExecuteTaskRequest struct {
	QueryParams ExecuteTaskQueryParams
	// ExecuteTaskRequest
	Request shared.ApiextExecuteTaskRequest `request:"mediaType=application/json"`
}

type ExecuteTaskResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	ApiextExecuteTaskResponse *shared.ApiextExecuteTaskResponse
}
