// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"test/pkg/models/shared"
)

type GetPromptQueryParams struct {
	// ID of the prompt to retrieve.
	ID string `queryParam:"style=form,explode=true,name=id"`
}

type GetPromptRequest struct {
	QueryParams GetPromptQueryParams
}

type GetPromptResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	ApiextGetPromptResponse *shared.ApiextGetPromptResponse
}
