// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"test/pkg/models/shared"
)

type GetSessionRequest struct {
	// ID of the session to retrieve.
	ID string `queryParam:"style=form,explode=true,name=id"`
}

type GetSessionResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	ApiextGetSessionResponse *shared.ApiextGetSessionResponse
}
