// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// ApiextPermissionRoleID - Which role is assigned to this permission.
type ApiextPermissionRoleID string

const (
	ApiextPermissionRoleIDTeamAdmin        ApiextPermissionRoleID = "team_admin"
	ApiextPermissionRoleIDTeamDeveloper    ApiextPermissionRoleID = "team_developer"
	ApiextPermissionRoleIDTaskViewer       ApiextPermissionRoleID = "task_viewer"
	ApiextPermissionRoleIDTaskRequester    ApiextPermissionRoleID = "task_requester"
	ApiextPermissionRoleIDTaskExecuter     ApiextPermissionRoleID = "task_executer"
	ApiextPermissionRoleIDTaskAdmin        ApiextPermissionRoleID = "task_admin"
	ApiextPermissionRoleIDRunViewer        ApiextPermissionRoleID = "run_viewer"
	ApiextPermissionRoleIDRunbookViewer    ApiextPermissionRoleID = "runbook_viewer"
	ApiextPermissionRoleIDRunbookRequester ApiextPermissionRoleID = "runbook_requester"
	ApiextPermissionRoleIDRunbookExecuter  ApiextPermissionRoleID = "runbook_executer"
	ApiextPermissionRoleIDRunbookAdmin     ApiextPermissionRoleID = "runbook_admin"
	ApiextPermissionRoleIDSessionViewer    ApiextPermissionRoleID = "session_viewer"
	ApiextPermissionRoleIDSessionExecuter  ApiextPermissionRoleID = "session_executer"
	ApiextPermissionRoleIDSessionAdmin     ApiextPermissionRoleID = "session_admin"
	ApiextPermissionRoleIDResourceUser     ApiextPermissionRoleID = "resource_user"
	ApiextPermissionRoleIDDeployCreator    ApiextPermissionRoleID = "deploy_creator"
	ApiextPermissionRoleIDGroupAdmin       ApiextPermissionRoleID = "group_admin"
)

func (e ApiextPermissionRoleID) ToPointer() *ApiextPermissionRoleID {
	return &e
}

func (e *ApiextPermissionRoleID) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "team_admin":
		fallthrough
	case "team_developer":
		fallthrough
	case "task_viewer":
		fallthrough
	case "task_requester":
		fallthrough
	case "task_executer":
		fallthrough
	case "task_admin":
		fallthrough
	case "run_viewer":
		fallthrough
	case "runbook_viewer":
		fallthrough
	case "runbook_requester":
		fallthrough
	case "runbook_executer":
		fallthrough
	case "runbook_admin":
		fallthrough
	case "session_viewer":
		fallthrough
	case "session_executer":
		fallthrough
	case "session_admin":
		fallthrough
	case "resource_user":
		fallthrough
	case "deploy_creator":
		fallthrough
	case "group_admin":
		*e = ApiextPermissionRoleID(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ApiextPermissionRoleID: %v", v)
	}
}

type ApiextPermission struct {
	// Which action this permission applies to.
	Action *string `json:"action,omitempty"`
	// Which role is assigned to this permission.
	RoleID *ApiextPermissionRoleID `json:"roleID,omitempty"`
	// ID of the group  this permission applies to if assigned to a group.
	SubGroupID *string `json:"subGroupID,omitempty"`
	// ID of the user this permission applies to if assigned directly to a user.
	SubUserID *string `json:"subUserID,omitempty"`
}
